apiVersion: apps/v1
kind: Deployment
metadata:
  name: info-service-deployment
  labels:
    app: info-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: info-service
  template:
    metadata:
      labels:
        app: info-service
    spec:
      containers:
      - name: info-service
        image: alexohneander/info-service:0.0.3
        ports:
        - containerPort: 4000
