apiVersion: v1
kind: Service
metadata:
  name: info-service
  namespace: info-service
  labels:
    app.kubernetes.io/instance: info-service
  annotations:
spec:
  ports:
    - name: http
      protocol: TCP
      port: 4000
      targetPort: 4000
  selector:
    app: info-service